# @package agent
_target_: agent.ddpg.DrQV2Agent
name: ddpg
obs_type: ???
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
batch_size: 32
critic_target_tau: 0.01
update_every_steps: 2
use_wandb: ${use_wandb}
num_expl_steps: 6000
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 'linear(1.0,0.1,2000000)'
stddev_clip: 0.3
sequence_length: 1
nstep: 1
